FYP/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.FileProviders;
using FYPDraft.Models;
using System.Data;
using Microsoft.AspNetCore.Authorization;

namespace FYPDraft.Controllers
{
    public class EventController : Controller
    {
        public IActionResult Events()
        {
            if (User.IsInRole("Alumni"))
            {

                string sql = "SELECT * FROM Event WHERE Type='Alumni'";
                DataTable dt = DBUtl.GetTable(sql);
                return View(dt.Rows);
            }
            else if (User.IsInRole("Startup"))
            {

                string sql = "SELECT * FROM Event WHERE Type='Startup'";
                DataTable dt = DBUtl.GetTable(sql);
                return View(dt.Rows);
            }
            else
            {
                string sql = "SELECT * FROM Event";
                DataTable dt = DBUtl.GetTable(sql);
                return View(dt.Rows);
            }
        }


        #region "Event Add"
        public IActionResult EventAdd()
        {
            return View("Create");
        }

        [HttpPost]
        public IActionResult EventAdd(Event ev, IFormFile file)
        {
            if (!ModelState.IsValid)
            {
                ViewData["Message"] = "Invalid Input";
                ViewData["MsgType"] = "warning";
                return View("Create");
            }
            else
            {
                string filename = DoFileUpload(ev.File);
                string insert = @"INSERT INTO Event(Title, Description, StartDate, EndDate, Venue, Type, Category, FileName,EventPID, EventLength) VALUES('{0}', '{1}', '{2:yyyy-MM-dd HH:mm}','{3:yyyy-MM-dd HH:mm}', '{4}', '{5}', '{6}', '{7}' , {8},{9})";
                int res = DBUtl.ExecSQL(insert, ev.Title, ev.Description, ev.StartDate, ev.EndDate, ev.Venue, ev.Type, ev.Category, filename, 0, 0);
                if (res == 1)
                {
                    TempData["Message"] = "Event Successfully Added";
                    TempData["MsgType"] = "success";
                }
                else
                {
                    TempData["Message"] = DBUtl.DB_Message;
                    TempData["MsgType"] = "danger";
                }
                return RedirectToAction("Events");
            }
        }
        #endregion

        #region "Event Delete"

        public IActionResult Delete(string id)
        {
            string select = @"SELECT * FROM Event WHERE Id={0}";
            DataTable ds = DBUtl.GetTable(select, id);
            if (ds.Rows.Count != 1)
            {
                TempData["Message"] = "Event does not exist";
                TempData["MsgType"] = "warning";
            }
            else
            {
                string docFile = ds.Rows[0]["fileName"].ToString();
                string fullpath = Path.Combine(_env.WebRootPath, "files/" + docFile);
                System.IO.File.Delete(fullpath);

                string delete = "DELETE FROM Event WHERE Id={0}";
                int res = DBUtl.ExecSQL(delete, id);
                if (res == 1)
                {
                    TempData["Message"] = "Event Deleted";
                    TempData["MsgType"] = "success";
                }
                else
                {
                    TempData["Message"] = DBUtl.DB_Message;
                    TempData["MsgType"] = "danger";
                }
            }
            return RedirectToAction("Events");
        }
        #endregion

        #region "Event Update"
        public IActionResult Update(string id)
        {
            string select = "SELECT * FROM Event WHERE Id={0}";
            List<Event> list = DBUtl.GetList<Event>(select, id);
            if (list.Count == 1)
            {
                return View(list[0]);
            }
            else
            {
                TempData["Message"] = "Event not found";
                TempData["MsgType"] = "warning";
                return RedirectToAction("Events");
            }

        }
        [HttpPost]
        public IActionResult Update(Event ev)
        {
            ModelState.Remove("File");
            if (!ModelState.IsValid)
            {
                ViewData["Message"] = "Invalid Input";
                ViewData["MsgType"] = "warning";
                return View("Create", ev);
            }
            else
            {
                string update = @"UPDATE Event SET Title ='{1}',
                                            Description = '{2}',
                                            StartDate = '{3:yyyy-MM-dd HH:mm}',
                                            EndDate = '{4:yyyy-MM-dd HH:mm}',
                                            Venue = '{5}',
                                            Type = '{6}',
                                            Category = '{7}'
                                            WHERE Id ={0}";
                int res = DBUtl.ExecSQL(update, ev.Id, ev.Title, ev.Description, ev.StartDate, ev.EndDate, ev.Venue, ev.Type, ev.Category);
                if (res == 1)
                {
                    TempData["Message"] = "Event Updated";
                    TempData["MsgType"] = "success";
                }
                else
                {
                    TempData["Message"] = DBUtl.DB_Message;
                    TempData["MsgType"] = "danger";
                }
                return RedirectToAction("Events");
            }
        }
        #endregion

        #region "Event Details"
        [Authorize(Roles = "Alumni,Startup")]
        public IActionResult Details(int id)
        {
            string sql = @"SELECT * FROM Event WHERE Id={0}";
            List<Event> lstEvent = DBUtl.GetList<Event>(sql, id);
            if (lstEvent.Count == 1)
            {
                Event ev = lstEvent[0];
                return View("Details", ev);
            }
            else
            {
                TempData["Message"] = "Event record does not exist";
                TempData["MsgType"] = "warning";
                return RedirectToAction("Events");
            }
        }
        #endregion
        #region "Upload File"
        private string DoFileUpload(IFormFile file)
        {
            string fext = Path.GetExtension(file.FileName);
            string uname = Guid.NewGuid().ToString();
            string fname = uname + fext;
            string fullpath = Path.Combine(_env.WebRootPath, "files/" + fname);
            using (FileStream fs = new FileStream(fullpath, FileMode.Create))
            {
                file.CopyTo(fs);
            }
            return fname;

        }

        private IWebHostEnvironment _env;
        public EventController(IWebHostEnvironment environment)
        {
            _env = environment;
        }



    }
}
#endregion

FYP/Controllers/PortalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace FYPDraft.Controllers
{
    public class PortalController : Controller
    {
        public IActionResult Home()
        {
            return View();
        }
    }
}

FYP/Controllers/ProgramController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FYPDraft.Controllers
{
    public class ProgramController : Controller
    {
        [Authorize(Roles = "Admin,Alumni,Startup")]
        public IActionResult Calendar()
        {
            return View();
        }
    }
}

FYP/Views/Shared/PortalAdmin.cshtml
<nav class="navbar navbar-expand-lg navbar-dark bg-dark border-dark">

   <!-- Hamburger Menu -->
   <button class="navbar-toggler" type="button"
           data-toggle="collapse" data-target="#navbarSupportedContent"
           aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
   </button>

   <div class="collapse navbar-collapse" id="navbarSupportedContent">
       <ul class="nav nav-tabs mr-auto">
           <li class="nav-item">
               <a class="nav-link bg-dark border-light text-light" asp-controller="Portal" asp-action="Home">Home</a>
           </li>
           <li class="nav-item">
               <a class="nav-link bg-dark border-light text-light" asp-controller="Program" asp-action="Calendar">Program Calendar</a>
           </li>
           <li class="nav-item dropdown bg-dark">
               <a class="nav-link bg-dark border-light text-light dropdown-toggle" data-toggle="dropdown">Feedback</a>
               <div class="dropdown-menu bg-dark">
                   <a class="nav-link bg-dark text-light" asp-controller="Feedback" asp-action="Create">Create Form</a>
                   <a class="nav-link bg-dark text-light" asp-controller="Feedback" asp-action="Overview">Overview Results</a>
               </div>
           </li>
           <li class="nav-item dropdown bg-dark">
               <a class="nav-link bg-dark border-light text-light dropdown-toggle" data-toggle="dropdown">Event</a>
               <div class="dropdown-menu bg-dark">
                   <a class="nav-link bg-dark text-light" asp-controller="Event" asp-action="EventAdd">Create Event</a>
                   <a class="nav-link bg-dark text-light" asp-controller="Event" asp-action="Events">Manage Events</a>
               </div>
           </li>
           <li class="nav-item dropdown bg-dark">
               <a class="nav-link bg-dark border-light text-light dropdown-toggle" data-toggle="dropdown">User</a>
               <div class="dropdown-menu bg-dark">
                   <a class="nav-link bg-dark border-light text-light" asp-controller="Account" asp-action="Create">Create New Account</a>
                   <a class="nav-link bg-dark border-light text-light" asp-controller="Account" asp-action="ListUsers">Manage Existing Account</a>
               </div>
           </li>
       </ul>

      <ul class="nav navbar-nav ml-auto">
         <li>
            <p class="navbar-text text-light">
               Welcome @User.Identity.Name<br />
            </p>
         </li>
         <li>
            <a class="nav-link" asp-controller="Account" asp-action="Logoff">
               <i class="fa fa-sign-out"></i>
               Logout
            </a>
         </li>
         <li>
            &nbsp;&nbsp;&nbsp;
         </li>
      </ul>
   </div>
</nav>






FYP/Views/Shared/PortalAlumni.cshtml
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">

    <!-- Hamburger Menu -->
    <button class="navbar-toggler" type="button"
            data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="nav nav-tabs mr-auto">
            <li class="nav-item">
                <a class="nav-link bg-dark border-light text-light" asp-controller="Portal" asp-action="Home">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link bg-dark border-light text-light" asp-controller="Program" asp-action="Calendar">Program Calendar</a>
            </li>
            <li class="nav-item">
                <a class="nav-link bg-dark border-light text-light disabled" asp-controller="Feedback" asp-action="List">Feedback</a>
            </li>
            <li class="nav-item">
                <a class="nav-link bg-dark border-light text-light" asp-controller="Event" asp-action="Events">Event</a>
            </li>
            <li class="nav-item">
                <a class="nav-link bg-dark border-light text-light disabled" asp-controller="Notifications" asp-action="Messages">
                    Notifications <span class="badge badge-light"></span>
                    <span class="sr-only">Unread Messages</span>
                </a>
            </li>
            <li class="nav-item dropdown bg-dark">
                <a class="nav-link bg-dark border-light text-light dropdown-toggle" data-toggle="dropdown">Account Management</a>
                <div class="dropdown-menu bg-dark">
                    <a class="nav-link bg-dark border-light text-light" asp-controller="Account" asp-action="ResetPwd">Reset Password</a>
                </div>
            </li>
        </ul>

        <ul class="nav navbar-nav ml-auto">
            <li>
                <p class="navbar-text">
                    Welcome @User.Identity.Name<br />
                </p>
            </li>
            <li>
                <a class="nav-link bg-dark border-light text-light" asp-controller="Account" asp-action="Logoff">
                    <i class="fa fa-sign-out-alt"></i>
                    Logout
                </a>
            </li>
        </ul>
    </div>
</nav>








FYP/Views/Shared/PortalGuest.cshtml
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">

   <!-- Hamburger Menu -->
   <button class="navbar-toggler" type="button"
           data-toggle="collapse" data-target="#navbarSupportedContent"
           aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
   </button>

   <div class="collapse navbar-collapse" id="navbarSupportedContent">
       <ul class="nav nav-tabs mr-auto">
           <li class="nav-item">
               <a class="nav-link bg-dark border-light text-light" asp-controller="Portal" asp-action="Home">Home</a>
           </li>
       </ul>

      <ul class="nav nav-tabs ml-auto">
          <li>
              <a class="nav-link bg-dark border-light text-light" asp-controller="Account" asp-action="Login">
                  <i class="fa fa-sign-in-alt bg-dark "></i>
                  Login
              </a>
          </li>
      </ul>
   </div>
</nav>

FYP/Views/Shared/PortalStartup.cshtml
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">

   <!-- Hamburger Menu -->
   <button class="navbar-toggler" type="button"
           data-toggle="collapse" data-target="#navbarSupportedContent"
           aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
   </button>

   <div class="collapse navbar-collapse" id="navbarSupportedContent">
       <ul class="nav nav-tabs mr-auto">
           <li class="nav-item">
               <a class="nav-link bg-dark border-light text-light" asp-controller="Portal" asp-action="Home">Home</a>
           </li>
           <li class="nav-item">
               <a class="nav-link bg-dark border-light text-light" asp-controller="Program" asp-action="Calendar">Program Calendar</a>
           </li>
           <li class="nav-item">
               <a class="nav-link bg-dark border-light text-light" asp-controller="Feedback" asp-action="List">Feedback</a>
           </li>
           <li class="nav-item">
               <a class="nav-link bg-dark border-light text-light" asp-controller="Event" asp-action="Events">Event</a>
           </li>
           <li class="nav-item">
               <a class="nav-link bg-dark border-light text-light" asp-controller="Notifications" asp-action="Messages">
                   Notifications <span class="badge badge-dark text-light">1</span>
                   <span class="sr-only">Unread Messages</span>
               </a>
           </li>
           <li class="nav-item dropdown bg-dark">
               <a class="nav-link bg-dark border-light text-light dropdown-toggle" data-toggle="dropdown">Account Management</a>
               <div class="dropdown-menu bg-dark">
                   <a class="nav-link bg-dark border-light text-light" asp-controller="Account" asp-action="ResetPwd">Reset Password</a>
               </div>
           </li>
       </ul>

      <ul class="nav navbar-nav ml-auto">
         <li>
            <p class="navbar-text">
               Welcome @User.Identity.Name<br />
            </p>
         </li>
         <li>
            <a class="nav-link bg-dark border-light text-light" asp-controller="Account" asp-action="Logoff">
               <i class="fa fa-sign-out-alt"></i>
               Logout
            </a>
         </li>
      </ul>
   </div>
</nav>






FYP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>Tribe - Portal</title>
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/lib/jquery/jquery.validate.min.js"></script>
    <script src="~/lib/jquery/jquery.validate.unobtrusive.min.js"></script>
    <link href="~/lib/font-awesome/css/fontawesome.min.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/brands.min.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/solid.min.css" rel="stylesheet" />
    <script src="~/lib//dhtmlx/codebase/dhtmlxscheduler.js"></script>
    <script src="~/lib/dhtmlx/codebase/ext/dhtmlxscheduler_recurring.js"></script>
    <link href="~/lib/dhtmlx/codebase/dhtmlxscheduler_material.css" rel="stylesheet" type="text/css" charset="utf-8">
    <script src="~/lib/dhtmlx/codebase/ext/dhtmlxscheduler_readonly.js" type="text/javascript" charset="utf-8"></script>
    <link href="~/lib/moment/moment.min.js" />
    <style type="text/css">
        .dhx_cal_event div.dhx_footer,
        .dhx_cal_event.event_Alumni div.dhx_footer,
        .dhx_cal_event.event_Startup div.dhx_footer {
            background-color: transparent !important;
        }

        .dhx_cal_event .dhx_body {
            -webkit-transition: opacity 0.1s;
            transition: opacity 0.1s;
            opacity: 0.7;
        }

        .dhx_cal_event .dhx_title {
            line-height: 12px;
        }

        .dhx_cal_event_line:hover,
        .dhx_cal_event:hover .dhx_body,
        .dhx_cal_event.selected .dhx_body,
        .dhx_cal_event.dhx_cal_select_menu .dhx_body {
            opacity: 1;
        }

        .dhx_cal_event.event_Alumni div,
        .dhx_cal_event_line.event_Alumni {
            background-color: #C6D124 !important;
            border-color: #732d16 !important;
        }

        .dhx_cal_event.dhx_cal_editor.event_Alumni {
            background-color: #C6D124 !important;
        }

        .dhx_cal_event_clear.event_Alumni {
            color: #C6D124 !important;
        }

        .dhx_cal_event.event_Startup div,
        .dhx_cal_event_line.event_Startup {
            background-color: #28BA00 !important;
            border-color: #698490 !important;
        }

        .dhx_cal_event.dhx_cal_editor.event_Startup {
            background-color: #28BA00 !important;
        }

        .dhx_cal_event_clear.event_Startup {
            color: #28BA00 !important;
        }

        .filters_wrapper {
            font: 500 14px Roboto;
        }

            .filters_wrapper span {
                font-weight: bold;
                padding-right: 5px;
                color: rgba(0,0,0,0.7);
            }

            .filters_wrapper label {
                padding-right: 3px;
            }
    </style>
    @RenderSection("MoreScripts", false)
</head>
<body>
    @if (User.Identity.IsAuthenticated)
    {
        if (User.IsInRole("Admin"))
        {
            <Partial name="PortalAdmin" />
        }
        else if (User.IsInRole("Startup"))
        {
            <Partial name="PortalStartup" />
        }
        else
        {
            <Partial name="PortalAlumni" />
        }
    }
    else
    {
        <Partial name="PortalGuest" />
    }

    <div class="container-fluid">
        @RenderBody()

    </div>
    <footer class="fixed-bottom">
        <!-- Insert Company Footer -->
        <div class="bg-dark text-light text-center">
            Copyright 2020 by Republic Polytechnic. All rights reserved.
        </div>
    </footer>
    <script>
        $(document).ready(function () {
            $('.toast').toast('show');
        });
    </script>
</body>
</html>